[package]
name = "public-impl"
version = "0.1.0"
authors = ["rklaehn@protonmail.com"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"